# liquibase.properties
url=jdbc:h2:file:./data/db/webapp.db
username=user
password=password
driver=org.h2.Driver
changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml
outputChangeLogFile=src/main/resources/db/changelog/generated-changelog.xml
