spring.application.name=glicemiewebapp

# Abilita console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.devtools.restart.enabled=false


# Configurazione database
spring.datasource.url=jdbc:h2:file:./data/db/webapp.db
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=user
spring.datasource.password=password
# Disattiva completamente i log SQL di Hibernate
spring.jpa.show-sql=false

# Disattiva i log SQL, binding e statistiche di Hibernate
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
logging.level.org.hibernate.stat=OFF

# Configurazione JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update


# JWT Configuration
security.jwt.secret-key=calamarata-ricetta-originale-345thiasIIys7920kn
security.jwt.expiration-time=3600000



#SVILUPPO TOGLIERE PER BUILD

# Disabilita completamente la protezione frame (solo per sviluppo!)
spring.security.headers.frame=false

# Oppure permetti solo same origin
spring.h2.console.settings.web-allow-others=true